# Generated by Django 5.2.2 on 2026-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_alter_folder_unique_together_alter_folder_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='icon',
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
