# Generated by Django 5.2.2 on 2026-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_alter_folder_options_remove_folder_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='position',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='updated_at',
        ),
    ]
